barter_system/config/routes.rb
BarterSystem::Application.routes.draw do

  resources :swaps

  get 'create_swap/:id', as: 'create_swap', controller: 'swaps', action: 'create_new'

  resources :auctions

  devise_for :users
  
  get 'welcome', as: 'welcome', controller: 'root', action: 'welcome'

  get 'user_swaps', as: 'open_user_swaps', controller: 'swaps', action: 'open_for_user'

  get 'accept/:id', as: 'accept', controller: 'swaps', action: 'accept'
  get 'deny/:id', as: 'deny', controller: 'swaps', action: 'deny'

  root 'root#index', as: 'index'

end

barter_system/app/models/auction.rb
class Auction < ActiveRecord::Base
	require 'carrierwave/orm/activerecord'
	mount_uploader :image, AuctionPictureUploader
	validates :auction_name, :auction_description, :image, presence: true
	belongs_to :user
end

barter_system/app/models/swap.rb
class Swap < ActiveRecord::Base
end

barter_system/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :auctions
end

barter_system/app/controllers/account_management_controller.rb
class AccountManagementController < ApplicationController
end

barter_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :display_name
  end
end

barter_system/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.where(user_id: current_user.id)
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:auction_name, :auction_description, :user_id, :available, :image)
    end
end

barter_system/app/controllers/barter_controller.rb
class BarterController < ApplicationController
end

barter_system/app/controllers/root_controller.rb
class RootController < ApplicationController
	before_action :redirect_if_not_logged_in, only: [:index]
	skip_before_action :authenticate_user!

	def index
		@auctions = Auction.where(available: true)
	end

	def welcome
	end

	private

	def redirect_if_not_logged_in
		unless user_signed_in?
			redirect_to welcome_url
		end
	end

end

barter_system/app/controllers/swaps_controller.rb
class SwapsController < ApplicationController
  before_action :set_swap, only: [:show, :edit, :update, :destroy]

  # GET /swaps
  # GET /swaps.json
  def index
    @swaps = Swap.all
  end

  # GET /open_user_swaps
  def open_for_user
    @swaps = Swap.where(owner_id: current_user.id, state: "Open")
  end

  def accept
    @swap = Swap.find_by(id: params[:id])
    @swap.state = "Accepted"
    @swap.save!
    auction = Auction.find_by(id: @swap.auction_id)
    bid = Auction.find_by(id: @swap.offer_id)
    auctioneer = User.find_by(id: @swap.owner_id)
    bidder = User.find_by(id: @swap.bidder_id)
    auction.available = false
    bid.available = false
    auction.user = bidder
    bid.user = auctioneer
    auction.save!
    bid.save!
    redirect_to index_path, notice: 'Auction accepted!'
  end

  def deny
    @swap = Swap.find_by(id: params[:id])
    @swap.state = "Denied"
    @swap.save!
    redirect_to index_path, notice: 'Auction denied'
  end

  def create_new
    @swap = Swap.new
    if current_user.auctions.empty?
      redirect_to index_path, alert: "You don't have any items to bid!"
    end
  end

  # GET /swaps/1
  # GET /swaps/1.json
  def show
  end

  # GET /swaps/new
  def new
    @swap = Swap.new
  end

  # GET /swaps/1/edit
  def edit
  end

  # POST /swaps
  # POST /swaps.json
  def create
    @swap = Swap.new(swap_params)

    respond_to do |format|
      if @swap.save
        format.html { redirect_to index_path, notice: 'Swap was successfully created.' }
        format.json { render :show, status: :created, location: @swap }
      else
        format.html { render :new }
        format.json { render json: @swap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swaps/1
  # PATCH/PUT /swaps/1.json
  def update
    respond_to do |format|
      if @swap.update(swap_params)
        format.html { redirect_to @swap, notice: 'Swap was successfully updated.' }
        format.json { render :show, status: :ok, location: @swap }
      else
        format.html { render :edit }
        format.json { render json: @swap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swaps/1
  # DELETE /swaps/1.json
  def destroy
    @swap.destroy
    respond_to do |format|
      format.html { redirect_to swaps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swap
      @swap = Swap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swap_params
      params.require(:swap).permit(:auction_id, :offer_id, :state, :bidder_id, :owner_id)
    end
end

barter_system/app/helpers/account_management_helper.rb
module AccountManagementHelper
end

barter_system/app/helpers/application_helper.rb
module ApplicationHelper
end

barter_system/app/helpers/auctions_helper.rb
module AuctionsHelper
end

barter_system/app/helpers/barter_helper.rb
module BarterHelper
end

barter_system/app/helpers/root_helper.rb
module RootHelper
end

barter_system/app/helpers/swaps_helper.rb
module SwapsHelper
end

barter_system/app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
<% if @auction.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>
  <ul>
    <% @auction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  </ul>
  <% end %>
</div>
<% end %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :available, value: true %>
<!-- content begins -->
<div class="col-sm-10">
  <div id="mySystem">
    <div class="form-group">
      <label for="inputName" class="col-sm-4 control-label">Name of Item</label>
      <div class="col-sm-6">                               
        <%= f.text_field :auction_name, :class => "form-control", id: "inputName", placeholder: "Name" %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputIntroduction" class="col-sm-4 control-label">Dscription of Item</label>
      <div class="col-sm-6">
        <%= f.text_area :auction_description, columns: 20, id: "inputIntroduction", placeholder: "Description of Item" %>
      </div>
    </div>
    <div class="form-group">
      <label for="itempic" class="col-sm-4">Image of item</label>
      <div class="col-sm-6">
        <%= image_tag(@auction.image_url(:thumb)) if @auction.image? %>
        <%= f.file_field :image, id: "picture" %>
      </div>
    </div>
    <hr>
      <div class="actions">
          <%= f.submit %>
  </div>
</div>
<% end %>

barter_system/app/views/auctions/edit.html.erb
<%= render partial: 'shared/sidebar' %>

<div class="container-fluid">
	<div class="row">
		<h1>Edit item details</h1>
		<%= render 'form' %>

		<%= link_to 'Show', @auction %> |
		<%= link_to 'Back', auctions_path %>
	</div>
</div>

barter_system/app/views/auctions/index.html.erb
<%= render partial: 'shared/sidebar' %>


<div class="col-sm-10">
  <div id="mySystem">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <div align="left" style="float:left; margin-top:1.5%;">
          <span class="glyphicon glyphicon-list"></span> Your Items
        </div>
          <div align="right">
            <%= link_to 'New Auction', new_auction_path, { :class => "btn btn-lg btn-success", :role => "button" } %>
          </div>
      </div>
      <table class="table table-hover" id="bidding-table">
        <thead>
          <tr>
            <th>Picture</th>
            <th>Item name</th>
            <th>Item description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @auctions.each do |auction| %>
          <tr>
            <td>
              <div class="media">
                <%= image_tag(auction.image_url(:thumb) , class: "media-object") %>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= auction.auction_name %></h5>
              </div>
            </td>
            <td>
              <p><%= auction.auction_description %></p>
            </td>
            <td>
              <%= link_to 'Show', auction %>
              <%= link_to 'Edit', edit_auction_path(auction) %>
              <%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

barter_system/app/views/auctions/new.html.erb
<%= render partial: 'shared/sidebar' %>
<div class="container-fluid">
	<div class="row">
		<h3> Add a new Item</h3>
		<%= render 'form' %>

		<%= link_to 'Back', auctions_path %>
	</div>
</div>

barter_system/app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'shared/sidebar' %>


<div class="col-sm-10">
  <div id="mySystem">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-list"></span> <%= @auction.auction_name %>
      </div>
      <table class="table table-hover" id="bidding-table">
        <thead>
          <tr>
            <th>Picture</th>
            <th>Item description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <div class="media">
                <%= image_tag(@auction.image_url, :class => "media-object") %>
              </div>
            </td>
            <td>
              <p><%= @auction.auction_description %></p>
            </td>
            <td>
              <%= link_to 'Edit', edit_auction_path(@auction) %> |
			  <%= link_to 'Back', auctions_path %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

barter_system/app/views/layouts/_sidebar.html.erb
<!-- Sidebar begins -->
<div class="col-sm-3 col-md-2 sidebar">
    <div id="sidebar-nav">
        <div id="accounts-menu" class="list-group">
            <a href="#" class="list-group-item active">
                <span class="glyphicon glyphicon-user"></span><%= current_user.display_name %>
            </a>
            <a href="#" class="list-group-item">
                <span class="glyphicon glyphicon-envelope"></span> Edit Profile
            </a>
            <div class = "dropdown">
             <a href="#" class="list-group-item" data-toggle="dropdown">
                <span class="glyphicon glyphicon-exclamation-sign"></span>
                Notifications <span class = "badge"> 10 </span>
                                 <!--div id ="notice">
                                 <span class = "badge"> 10 </span>
                                 <!--span class="caret"></span-->
                             </a>                            
                         </div>                  
                     </div>
                     <br>
                     <div id="barter-menu">
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-search"></span> Search
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-home"></span> Barter System
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-check"></span> Bidding Items
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-share"></span> Selling Items
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-bullhorn"></span> Swaping Rules
                        </a>
                        <a href="#" class="list-group-item">
                            <span class="glyphicon glyphicon-tower"></span> Community
                        </a>
                    </div>
                </div>
            </div><!-- Sidebar ends -->

barter_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>BarterSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <div id = "wrap">
        <!-- Justified Nav -->
        <div class="container">
            <div class="masthead">
                <h3 class="text-muted">MINES Barter System</h3>
                <ul class="nav nav-justified">
                    <li><%= link_to "Home", index_path %></li>
                    <% if user_signed_in? %>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                    <li><%= link_to "Sign In", new_user_session_path %></li>
                    <% end %>
                <!-- <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li> -->
            </ul>
        </div>
    <!-- </div> -->
    <div class="container-fluid">
        <div class="row">
            <!-- Page Content -->
            <%= yield %>
        </div>
    </div>        
</div>
<div id="footer">
    <div class="container">
        <p class="text-muted credit"><a href="http://eecs.mines.edu/Courses/csci446/">Final Project of CSCI446 Web Application</a> by Hunter Lang, Timothy Nygren and Wenjun Ji</p>
    </div>
</div>
</body>
</html>

barter_system/app/views/root/index.html.erb
<%= render partial: 'shared/sidebar' %>
<!-- content begins -->
<div class="col-sm-10">
    <div id="mySystem">
        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list"></span> Auctioning Items
            </div>
            <!-- Table -->
            <table class="table table-hover" id="bidding-table">
                <thead>
                    <th>Auctioning Items</th>
                    <th>Seller</th>
                    <th></th>
                </thead>
                <tbody>
                    <% @auctions.each do |auction| %>
                    <tr>
                        <td>
                            <div class="media">
                                <a href="#" class="pull-left">
                                    <%= image_tag(auction.image_url(:thumb) , class: "media-object") %>
                                </a>
                                <div class="media-body">
                                    <h5 class="media-heading"><a href=""><%= auction.auction_name %></a></h5>
                                    <p><%= auction.auction_description %></p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <%= auction.user.display_name %>
                        </td>
                        <td>
                            <%= link_to 'Bid', create_swap_path(auction.id), {:class => "btn btn-warning btn-xs"} %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div><!-- content ends -->

barter_system/app/views/root/welcome.html.erb
<!-- Jumbotron -->
      <div class="jumbotron">
        <h1>THE BARTER SYSTEM</h1>
        <p class="lead">This system is used for mines students. A variety of merchandise is available. </p>
        <p><%= link_to "Sign Up Today", new_user_registration_path, {:class => "btn btn-lg btn-success", :role => "button"} %></p>
      </div>

<!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('books.jpg') %>
                <div class="caption">
                    <h2>Swap Books</h2>
          <p>You can swap books here.</p>
          <p><%= link_to "Get started today!", new_user_registration_path, {:role => "button", :class => "btn btn-primary" } %></p>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('Digital_Device.gif') %>
                <div class="caption">
                    <h2>Swap Digital Devices</h2>
          <p>You can swap electronic devices here.</p>
          <p><%= link_to "Get started today!", new_user_registration_path, {:role => "button", :class => "btn btn-primary" } %></p>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('Minecraft.png') %>
                <div class="caption">
                    <h2>Swap Video Games</h2>
          <p>You can swap video games here.</p>
          <p><%= link_to "Get started today!", new_user_registration_path, {:role => "button", :class => "btn btn-primary" } %></p>
                    </p>
                </div>
            </div>
        </div>
      </div>

barter_system/app/views/shared/_sidebar.html.erb
<!-- Sidebar begins -->
<div class="col-sm-3 col-md-2 sidebar">
    <div id="barter-menu">
        <a href="<%= index_path %>" class="list-group-item active">
            <span class="glyphicon glyphicon-user"></span> <%= current_user.display_name %>
        </a>
        <a href="<%= auctions_url %>" class="list-group-item">
            <span class="glyphicon glyphicon-tower"></span> Your Items
        </a>
        <a href="<%= open_user_swaps_url %>" class="list-group-item">
            <span class="glyphicon glyphicon-share"></span> Open Swaps
        </a>
        <a href="<%= swaps_url %>" class="list-group-item">
            <span class="glyphicon glyphicon-check"></span> All Swaps
        </a>
    </div>
</div>

barter_system/app/views/swaps/_form.html.erb
<%= form_for(@swap) do |f| %>
  <% if @swap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swap.errors.count, "error") %> prohibited this swap from being saved:</h2>

      <ul>
      <% @swap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :bidder_id, value: current_user.id %>
  <%= f.hidden_field :state, value: "Open" %>
  <div class="field">
    <%= f.label :auction_id %><br>
    <%= f.number_field :auction_id %>
  </div>
  <div class="field">
    <%= f.label :offer_id %><br>
    <%= f.number_field :offer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

barter_system/app/views/swaps/create_new.html.erb
<%= render partial: 'shared/sidebar' %>

<% @item = Auction.find_by(id: params[:id]) %>
<div class="col-sm-10">
	<div id="mySystem">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-list"></span> Select an Item to trade
			</div>
			<div align="center">
				<%= form_for(@swap) do |f| %>
				<% @first_auction = current_user.auctions[0] %>
				<%= collection_radio_buttons(:swap, :offer_id, current_user.auctions, :id, :auction_name, checked: @first_auction.id) do |button| %>
				<%= button.label(:"data-value" => button.value) { button.radio_button + button.text } %><br>
				<% end %>
				<%= f.hidden_field :state, :value => "Open" %>
				<%= f.hidden_field :bidder_id, :value => current_user.id %>
				<%= f.hidden_field :auction_id, :value => params[:id] %>
				<%= f.hidden_field :owner_id, :value => @item.user.id %>
				<%= f.submit %> 
				<% end %>
			</div>
		</div>
	</div>
</div>

barter_system/app/views/swaps/edit.html.erb
<h1>Editing swap</h1>

<%= render 'form' %>

<%= link_to 'Show', @swap %> |
<%= link_to 'Back', swaps_path %>

barter_system/app/views/swaps/index.html.erb
<%= render partial: 'shared/sidebar' %>
<div class="col-sm-10">
  <div id="mySystem">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-list"></span> All Swaps
      </div>
      <table class="table table-hover" id="bidding-table">
        <thead>
          <tr>
            <th>Auctioned Item</th>
            <th>Owner</th>
            <th>Bidding Item</th>
            <th>Bidder</th>
            <th>State of Transaction</th>
          </tr>
        </thead>
        <tbody>
          <% @swaps.each do |swap| %>
          <tr>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= Auction.find_by(id: swap.auction_id).auction_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= User.find_by(id: swap.owner_id).display_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= Auction.find_by(id: swap.offer_id).auction_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= User.find_by(id: swap.bidder_id).display_name %></h5>
              </div>              
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading" align="center"><%= swap.state %></h5>
              </div>   
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

barter_system/app/views/swaps/new.html.erb
<h1>New swap</h1>

<%= render 'form' %>

<%= link_to 'Back', swaps_path %>

barter_system/app/views/swaps/open_for_user.html.erb
<%= render partial: 'shared/sidebar' %>


<div class="col-sm-10">
  <div id="mySystem">
    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-list"></span> Open Swaps
      </div>
      <table class="table table-hover" id="bidding-table">
        <thead>
          <tr>
            <th>Auctioned Item</th>
            <th>Owner</th>
            <th>Bidding Item</th>
            <th>Bidder</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @swaps.each do |swap| %>
          <tr>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= Auction.find_by(id: swap.auction_id).auction_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= User.find_by(id: swap.owner_id).display_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= Auction.find_by(id: swap.offer_id).auction_name %></h5>
              </div>
            </td>
            <td>
              <div class="media-body">
                <h5 class="media-heading"><%= User.find_by(id: swap.bidder_id).display_name %></h5>
              </div>              
            </td>
            <td>
              <%= link_to 'Accept', accept_path(swap.id) %>
              <%= link_to 'Decline', deny_path(swap.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

barter_system/app/views/swaps/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'shared/sidebar' %>
<p>
  <strong>Auction:</strong>
  <%= @swap.auction_id %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @swap.offer_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @swap.state %>
</p>

<%= link_to 'Edit', edit_swap_path(@swap) %> |
<%= link_to 'Back', swaps_path %>

barter_system/app/views/welcome/index.html.erb
<!-- Jumbotron -->
      <div class="jumbotron">
        <h1>THE BARTER SYSTEM</h1>
        <p class="lead">This system is used for mines students. A variety of maerchandise is available. </p>
        <p><%= link_to "Sign Up Today", new_user_registration_path, {:class => "btn btn-lg btn-success", :role => "button"} %> </p>
      </div>

<!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('books.jpg') %>
                <div class="caption">
                    <h2>Swap Books</h2>
          <p>You can swap books here.</p>
          <p><a class="btn btn-primary" href="#" role="button">Bid</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('Digital_Device.gif') %>
                <div class="caption">
                    <h2>Swap Digital Devices</h2>
          <p>You can swap electronic devices here.</p>
          <p><a class="btn btn-primary" href="#" role="button">Bid</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="thumbnail">
                <%= image_tag('Minecraft.png') %>
                <div class="caption">
                    <h2>Swap Video Games</h2>
          <p>You can swap video games here.</p>
          <p><a class="btn btn-primary" href="#" role="button">Bid</a>
                    </p>
                </div>
            </div>
        </div>
      </div>